# Generated by Django 4.2.11 on 2024-06-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/media/imageup/'),
        ),
    ]
