# Generated by Django 4.2.11 on 2024-06-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carmodel', '0002_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
