# Generated by Django 4.2.11 on 2024-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carmodel', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='userquantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
