# Generated by Django 4.2.11 on 2024-06-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carmodel', '0005_purchace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='userquantity',
        ),
    ]
