# Generated by Django 4.2.11 on 2024-06-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carmodel', '0006_remove_car_userquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchace',
            name='Purchace_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
