# Generated by Django 4.2.11 on 2024-06-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carmodel', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='carmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carmodel.car'),
        ),
    ]
