# Generated by Django 4.2.11 on 2024-06-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
